== Etherpad Container for Red Hat OpenShift

This repository provides an Etherpad Container to be run on Red Hat OpenShift. While you can build it yourself the easiest way to set up is to just deploy the image:

[source,bash]
----
oc new-project etherpad --display-name "Shared Etherpad"

oc new-app mysql-persistent --param MYSQL_USER=ether --param MYSQL_PASSWORD=ether --param MYSQL_DATABASE=ether --param VOLUME_CAPACITY=10Gi --param MYSQL_VERSION=8.0

sleep 15

# oc new-app -f etherpad-template.yaml -p DB_USER=ether -p DB_PASS=ether -p DB_DBID=ether -p DB_PORT=3306 -p DB_HOST=mysql -p ADMIN_PASSWORD=secret
oc new-app -f https://raw.githubusercontent.com/wkulhanek/docker-openshift-etherpad/master/etherpad-template.yaml -p DB_USER=ether -p DB_PASS=ether -p DB_DBID=ether -p DB_PORT=3306 -p DB_HOST=mysql -p ADMIN_PASSWORD=secret -p ETHERPAD_IMAGE=quay.io/wkulhanek/etherpad:1.8.3
----


oc new-app --template=postgresql-persistent --param POSTGRESQL_USER=ether --param POSTGRESQL_PASSWORD=ether --param POSTGRESQL_DATABASE=etherpad --param POSTGRESQL_VERSION=10 --param VOLUME_CAPACITY=10Gi --labels=app=etherpad_db

oc new-app -f https://raw.githubusercontent.com/wkulhanek/docker-openshift-etherpad/master/etherpad-template.yaml -p DB_TYPE=postgres -p DB_HOST=postgresql -p DB_PORT=5432 -p DB_DATABASE=etherpad -p DB_USER=ether -p DB_PASS=ether -p ADMIN_PASSWORD=secret -p ETHERPAD_IMAGE=quay.io/wkulhanek/etherpad:1.8.3

oc new-app -f template.yaml -p DB_TYPE=postgres -p DB_HOST=postgresql -p DB_PORT=5432 -p DB_DATABASE=etherpad -p DB_USER=ether -p DB_PASS=ether -p ADMIN_PASSWORD=secret -p ETHERPAD_IMAGE=quay.io/wkulhanek/etherpad:1.8.3
